### PR TITLE
Add more official icons

### PR DESCRIPTION
**Pull request by kerrtravers**
Adds more official twitter icons, will do the same with Github icons later.

### CODE REVIEW

**Review by radioblahaj — CHANGES_REQUESTED** [review]
Please try to add more images. As you do, I will merge this pull request. I can give you access to add images. Thanks for your work.

**Comment by kerrtravers** [comment]
I don't have time to work on this as a full project, I was just making a few changes.

**Comment by kerrtravers** [comment]
@redmangospros

**Comment by radioblahaj** [comment]
Okay. Thanks. I will merge

**Pull request merged**
